{{- range $i, $cb := .Values.driftCallbacks }}
{{- if $cb.ca.cert }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kausality.fullname" $ }}-callback-ca-{{ $i }}
  labels:
    {{- include "kausality.labels" $ | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ $cb.ca.cert | b64enc }}
{{- end }}
{{- end }}
