{{- if .Values.certificates.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "kausality.certificateSecretName" . }}
  labels:
    {{- include "kausality.webhookLabels" . | nindent 4 }}
spec:
  secretName: {{ include "kausality.certificateSecretName" . }}
  dnsNames:
    - {{ include "kausality.webhookServiceName" . }}
    - {{ include "kausality.webhookServiceName" . }}.{{ .Release.Namespace }}
    - {{ include "kausality.webhookServiceName" . }}.{{ .Release.Namespace }}.svc
    - {{ include "kausality.webhookServiceName" . }}.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    name: {{ .Values.certificates.certManager.issuerRef.name }}
    kind: {{ .Values.certificates.certManager.issuerRef.kind }}
{{- end }}
