apiVersion: v1
kind: Service
metadata:
  name: {{ include "kausality.webhookServiceName" . }}
  labels:
    {{- include "kausality.webhookLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: webhook
      protocol: TCP
      name: https
  selector:
    {{- include "kausality.webhookSelectorLabels" . | nindent 4 }}
